"""Added gender to 'Races'

Revision ID: 73e1655671c4
Revises: feb9c8300f11
Create Date: 2025-07-09 19:40:33.862396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e1655671c4'
down_revision: Union[str, None] = 'feb9c8300f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('gender', sa.Enum('M', 'F', 'A', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'gender')
    # ### end Alembic commands ###
