"""Store codex as integer

Revision ID: 7704eab24287
Revises: 73e1655671c4
Create Date: 2025-07-10 16:49:13.969838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7704eab24287'
down_revision: Union[str, None] = '73e1655671c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE races ALTER COLUMN race_codex TYPE INTEGER USING (race_codex::integer)")
    # above is potentially dangerous if there are non-numeric codexes, but there shouldn't be

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'race_codex',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
