"""empty message

Revision ID: 8dcbc5e4dba0
Revises: de0a0f48a21f
Create Date: 2025-07-01 20:30:30.377593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcbc5e4dba0'
down_revision: Union[str, None] = 'de0a0f48a21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race_results', sa.Column('run1_time', sa.Float(), nullable=True))
    op.add_column('race_results', sa.Column('run2_time', sa.Float(), nullable=True))
    op.drop_column('race_results', 'race_points')
    op.add_column('races', sa.Column('nation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'nation')
    op.add_column('race_results', sa.Column('race_points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('race_results', 'run2_time')
    op.drop_column('race_results', 'run1_time')
    # ### end Alembic commands ###
