"""Add fis_db_id to RaceResult

Revision ID: 9f7ea09a6e56
Revises: reinitialize_database
Create Date: 2025-06-24 15:10:27.563706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7ea09a6e56'
down_revision: Union[str, None] = 'reinitialize_database'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athlete_points', 'calculated_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('race_results', sa.Column('fis_db_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race_results', 'fis_db_id')
    op.alter_column('athlete_points', 'calculated_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
