"""add_race_course_details

Revision ID: de0a0f48a21f
Revises: 8b964425334c
Create Date: 2025-06-30 14:30:10.960544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0a0f48a21f'
down_revision: Union[str, None] = '8b964425334c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('start_altitude', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('finish_altitude', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('gates', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('turning_gates', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('homologation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'homologation')
    op.drop_column('races', 'turning_gates')
    op.drop_column('races', 'gates')
    op.drop_column('races', 'length')
    op.drop_column('races', 'finish_altitude')
    op.drop_column('races', 'start_altitude')
    # ### end Alembic commands ###
