"""Support second-run gate counts

Revision ID: de683f329984
Revises: de0a0f48a21f
Create Date: 2025-07-03 19:26:13.612980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de683f329984'
down_revision: Union[str, None] = 'de0a0f48a21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'gates', new_column_name='gates1')
    op.alter_column('races', 'turning_gates', new_column_name='turning_gates1')
    op.add_column('races', sa.Column('gates2', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('turning_gates2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'gates1', new_column_name='gates')
    op.alter_column('races', 'turning_gates1', new_column_name='turning_gates')
    op.drop_column('races', 'turning_gates2')
    op.drop_column('races', 'gates2')
    # ### end Alembic commands ###
