"""Add ski club, per-discipline status fields to AthletePoints

Revision ID: feb9c8300f11
Revises: de683f329984
Create Date: 2025-07-05 15:13:17.923084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb9c8300f11'
down_revision: Union[str, None] = 'de683f329984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete_points', sa.Column('sl_status', sa.String(), nullable=True))
    op.add_column('athlete_points', sa.Column('gs_status', sa.String(), nullable=True))
    op.add_column('athlete_points', sa.Column('sg_status', sa.String(), nullable=True))
    op.add_column('athlete_points', sa.Column('dh_status', sa.String(), nullable=True))
    op.add_column('athlete_points', sa.Column('ac_status', sa.String(), nullable=True))
    op.add_column('athlete_points', sa.Column('ski_club', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete_points', 'ski_club')
    op.drop_column('athlete_points', 'ac_status')
    op.drop_column('athlete_points', 'dh_status')
    op.drop_column('athlete_points', 'sg_status')
    op.drop_column('athlete_points', 'gs_status')
    op.drop_column('athlete_points', 'sl_status')
    # ### end Alembic commands ###
