# fis_constants.py
from enum import Enum

BASE_URL: str = "https://www.fis-ski.com/DB"
DATA_URL: str = "https://data.fis-ski.com"
FIS_URL: str = "https://www.fis-ski.com"

class FisSector(Enum):
    """FIS Sector"""
    ALPINE = 'AL'
    CROSS_COUNTRY = 'CC'
    SKI_JUMPING = 'JP'
    NORDIC_COMBINED = 'NK'
    FREESTYLE = 'FS'
    FREERIDE = 'FR'
    SNOWBOARD = 'SB'
    SPEED_SKIING = 'SS'
    GRASS_SKIING = 'GS'
    TELEMARK = 'TM'
    MASTERS = 'MA'
    PARA_CROSS_COUNTRY = 'PCC'
    PARA_ALPINE_SKIING = 'PAL'
    PARA_SNOWBOARD = 'PSB'

class FisCategory(Enum):
    """FIS Category"""
    OLYMPIC_WINTER_GAMES = 'OWG'
    WORLD_CHAMPIONSHIPS = 'WSC'
    WORLD_CUP = 'WC'
    WORLD_CUP_SPEED_EVENT = 'COM'
    FIS_JUNIOR_WORLD_SKI_CHAMPIONSHIPS = 'WJC'
    WORLD_CUP_QUALIFICATION = 'WQUA'
    YOUTH_OLYMPIC_WINTER_GAMES = 'YOG'
    AUSTRALIAN_NEW_ZEALAND_CUP = 'ANC'
    EUROPEAN_CUP = 'EC'
    FAR_EAST_CUP = 'FEC'
    NOR_AM_CUP = 'NAC'
    SOUTH_AMERICAN_CUP = 'SAC'
    EUROPEAN_CUP_SPEED_EVENT = 'ECOM'
    EUROPEAN_CUP_QUALIFICATION = 'EQUA'
    NATIONAL_CHAMPIONSHIPS = 'NC'
    FIS = 'FIS'
    FIS_QUALIFICATION = 'FQUA'
    ASIAN_WINTER_GAMES = 'AWG'
    UNIVERSIADE = 'UVS'
    JUNIOR = 'JUN'
    NATIONAL_JUNIOR_CHAMPIONSHIPS = 'NJC'
    NATIONAL_JUNIOR_RACE = 'NJR'
    CITIZEN = 'CIT'
    UNIVERSITY = 'UNI'
    CHILDREN = 'CHI'
    PARA_EVENTS = 'PARA'
    DISABLED_ATHLETES_EVENTS = 'DAR'
    CORPORATE = 'CORP'
    MILITARY_AND_POLICE = 'CISM'
    ENTRY_LEAGUE_FIS = 'ENL'
    EXHIBITION = 'EXI'
    EUROPEAN_YOUTH_OLYMPIC_FESTIVAL = 'EYOF'
    NATION_GRAND_PRIX = 'NGP'
    TRAINING = 'TRA'

